# Generated by Django 6.0.7 on 2026-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional. Shown as the image caption/alt text if provided.', max_length=150)),
                ('image', models.ImageField(help_text='Recommended: square or landscape photo, at least 600px wide.', upload_to='clients/')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this photo from the site without deleting it.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the gallery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
