# Generated by Django 6.1 on 2026-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(help_text='e.g. Cardiologist, Orthopedic Surgeon, Oncologist', max_length=150)),
                ('photo', models.ImageField(blank=True, help_text='Square or portrait photo recommended', null=True, upload_to='doctors/')),
                ('hospital', models.CharField(blank=True, help_text='Hospital or clinic name (can later become a ForeignKey)', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short professional bio shown on the card / detail')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Years of experience (optional)', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage or medical page featured section')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide without deleting')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'name'],
            },
        ),
    ]
